### ISSUE TITLE
Exception caught by image resource service, Bad state: Future already completed

### ISSUE THREAD

**Issue by sgon00** [renancaraujo/photo_view#14]
I saw the following exceptions thrown in the console:

```
I/flutter ( 2935): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 2935): The following StateError was thrown by an image listener:
I/flutter ( 2935): Bad state: Future already completed
I/flutter ( 2935): 
I/flutter ( 2935): When the exception was thrown, this was the stack:
I/flutter ( 2935): #1      _PhotoViewState._getImage.<anonymous closure> (package:photo_view/photo_view.dart:42:17)
I/flutter ( 2935): #2      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:278:17)
I/flutter ( 2935): #3      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:519:5)
I/flutter ( 2935): #4      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:512:7)
I/flutter ( 2935): <asynchronous suspension>
I/flutter ( 2935): #5      MultiFrameImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:528:7)
I/flutter ( 2935): #6      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:158:25)
I/flutter ( 2935): #7      _PhotoViewState._getImage (package:photo_view/photo_view.dart:44:12)
I/flutter ( 2935): #8      _PhotoViewState.build (package:photo_view/photo_view.dart:69:17)
I/flutter ( 2935): #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter ( 2935): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter ( 2935): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #33     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3968:11)
I/flutter ( 2935): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4772:32)
I/flutter ( 2935): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #54     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #73     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #80     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #99     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #106    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #109    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #121    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #124    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #133    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #139    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #140    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #144    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #145    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #146    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #147    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #150    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #151    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #155    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #156    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #157    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #159    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #161    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #163    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #164    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #165    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #166    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #167    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #171    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #172    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #173    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #175    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 2935): #176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #179    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #187    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #188    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #189    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #190    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #192    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #193    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 2935): #194    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 2935): #195    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 2935): #196    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 2935): #197    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 2935): #198    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4450:32)
I/flutter ( 2935): #199    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4782:17)
I/flutter ( 2935): #200    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 2935): #201    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 2935): #202    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 2935): #203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #204    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #205    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 2935): #206    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 2935): #207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #208    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #209    ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 2935): #210    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 2935): #211    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 2935): #212    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 2935): #213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #214    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #215    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 2935): #216    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 2935): #217    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 2935): #218    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 2935): #219    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 2935): #220    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 2935): #221    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 2935): #222    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 2935): #223    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 2935): #224    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 2935): #225    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 2935): #226    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 2935): #227    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 2935): #228    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 2935): #229    _invoke (dart:ui/hooks.dart:128:13)
I/flutter ( 2935): #230    _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter ( 2935): (elided one frame from package dart:async)
I/flutter ( 2935): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by sgon00** [comment]
@renancaraujo yeah, I am using 0.0.4, because I am using the new feature 
```
minScale: PhotoViewScaleBoundary.contained
```

**Comment by renancaraujo** [comment]
Once again, if you could upload the code of this example, it would help me to figure out what is causing this problem.

**Comment by An-uking** [comment]
@renancaraujo  use the plugin in pageview component
