### ISSUE TITLE
"null boolean" exception thrown from PhotoViewInline

### ISSUE THREAD

**Issue by KevinTheGray** [renancaraujo/photo_view#38]
If you don't specify the `gaplessPlayback` parameter in PhotoViewInline, the following exception is thrown.  I believe the fix would be that you need to specify a default value for the PhotoViewInline constructor.

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Container(bg: BoxDecoration(color: Color(0xff000000))):
flutter: Failed assertion: boolean expression must not be null
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _ImageState._updateSourceStream (package:flutter/src/widgets/image.dart:610:17)
flutter: #1      _ImageState._resolveImage (package:flutter/src/widgets/image.dart:591:5)
flutter: #2      _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:561:5)
flutter: #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3803:12)
flutter: #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
flutter: #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
flutter: #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
flutter: #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
flutter: #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
flutter: #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
flutter: #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
flutter: #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
flutter: #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
flutter: #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
flutter: #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #57     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:670:20)
flutter: #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #63     _invoke (dart:ui/hooks.dart:139:13)
flutter: #64     _drawFrame (dart:ui/hooks.dart:128:3)
```

<img width="413" alt="screen shot 2018-10-08 at 10 50 27 am" src="https://user-images.githubusercontent.com/9346834/46616294-34b06900-cae8-11e8-9280-7cef2813ce39.png">

flutter doctor

```
[✓] Flutter (Channel master, v0.9.7-pre.61, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.7-pre.61 at /Users/KG/Developer/Flutter/flutter
    • Framework revision 2d81adf74c (2 days ago), 2018-10-05 22:29:37 -0700
    • Engine revision 572fa5646a
    • Dart version 2.1.0-dev.6.0.flutter-c6254163dc

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```

**Comment by renancaraujo** [comment]
Fixed in #39
